prompt_path: 'generation_prompts/character_64.csv'     



negative_prompt: ""
unconditional_prompt: ""             
width: 512
height: 512
num_inference_steps: 50
guidance_scale: 7.5
seed: 0
generate_num: 5
gate_rank: 16

save_path: "generated_images/#/character/{}_{}_{}.png"