- action: erase_with_la
  batch_size: 1
  dynamic_resolution: true
  guidance_scale: '0.3'
  la_strength: 0.0
  neutral: a celebrity
  positive: a celebrity
  resolution: 512
  sampling_batch_size: 32
  target: a celebrity
  unconditional: ''
